name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/atd
          chmod 600 $HOME/.ssh/atd
          ssh-keyscan 208.109.188.104 >> $HOME/.ssh/known_hosts
    
      - name: Git pull
        env:
          SSH_USERNAME: ${{ secrets.USERNAME }}
        run: |
          ssh -i $HOME/.ssh/atd $SSH_USERNAME@208.109.188.104 "cd /home/$SSH_USERNAME/atd-angular && git pull"

      - name: Deploy to VPS
        run: |
          ssh -i $HOME/.ssh/atd $SSH_USERNAME@208.109.188.104 "cd /home/$SSH_USERNAME/atd-angular && chown -R $SSH_USERNAME:$SSH_USERNAME /home/$SSH_USERNAME/atd-angular/dist && export PATH=$PATH:/home/$SSH_USERNAME/.nvm/versions/node/v21.0.0/bin && npm install && ng build --configuration production --aot"
        env:
          SSH_USERNAME: ${{ secrets.USERNAME }}

      - name: Copy dist to /var/www/html/
        run: |
          ssh -i $HOME/.ssh/atd $SSH_USERNAME@208.109.188.104 "cd /home/$SSH_USERNAME/atd-angular && export PATH=$PATH:/home/$SSH_USERNAME/.nvm/versions/node/v21.0.0/bin && chown -R atdadmin:atdadmin /var/www/html && if [ -d /var/www/html/atd-app ]; then rm -r /var/www/html/atd-app; fi && cp -r /home/atdadmin/atd-angular/dist/atd-app/ /var/www/html/"
        env:
          SSH_USERNAME: ${{ secrets.USERNAME }}